"""Add image path to Post model

Revision ID: 91fbd9ab2f71
Revises: ad1186302cd7
Create Date: 2026-04-17 06:12:56.639138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91fbd9ab2f71'
down_revision: Union[str, Sequence[str], None] = 'ad1186302cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_path')
    # ### end Alembic commands ###
